import { TemplateDefinition, TemplateSeedContext, SeedRecordResult } from '../types';
import { TemplateImageGenerator } from '../TemplateImageGenerator';

export const crmTemplate: TemplateDefinition = {
  id: 'crm',
  name: 'SaaS / CRM',
  tagline: 'High-velocity sales pipeline with leads, deals, companies & activities',
  description:
    'Comprehensive customer relationship management schema pre-seeded with B2B companies, logo marks, qualified prospects, deal stages, and activity timelines.',
  icon: '👥',
  badge: 'Pipeline & Deals',
  aliases: ['saas', 'crm', 'pipeline', 'sales'],
  stats: {
    collections: 4,
    records: 42,
    images: 6,
  },
  collections: [
    // 1. Companies
    {
      name: 'companies',
      dto: {
        name: 'companies',
        type: 'base',
        listRule: '@request.auth.id != ""',
        viewRule: '@request.auth.id != ""',
        createRule: '@request.auth.id != ""',
        updateRule: '@request.auth.id != ""',
        deleteRule: '@request.auth.id != ""',
        schema: [
          { id: 'f_comp_name', name: 'name', type: 'text', required: true, unique: true },
          { id: 'f_comp_domain', name: 'domain', type: 'text', required: true },
          {
            id: 'f_comp_ind',
            name: 'industry',
            type: 'select',
            options: { values: ['Software & SaaS', 'Healthcare', 'Fintech', 'E-Commerce', 'Education', 'Clean Energy', 'Logistics'] },
          },
          {
            id: 'f_comp_size',
            name: 'size',
            type: 'select',
            options: { values: ['1-10', '11-50', '51-200', '201-500', '500+'] },
          },
          { id: 'f_comp_rev', name: 'annualRevenue', type: 'number' },
          { id: 'f_comp_logo', name: 'logo', type: 'file' },
          { id: 'f_comp_site', name: 'website', type: 'url' },
          { id: 'f_comp_city', name: 'city', type: 'text' },
          { id: 'f_comp_country', name: 'country', type: 'text' },
        ],
      },
      seed: async (_ctx: TemplateSeedContext): Promise<SeedRecordResult[]> => {
        const companiesData = [
          {
            id: 'comp_01',
            name: 'Nexus Digital Systems',
            domain: 'nexusdigital.io',
            industry: 'Software & SaaS',
            size: '51-200',
            annualRevenue: 18500000,
            website: 'https://nexusdigital.io',
            city: 'San Francisco',
            country: 'United States',
          },
          {
            id: 'comp_02',
            name: 'Apex Financial Technologies',
            domain: 'apexfin.com',
            industry: 'Fintech',
            size: '201-500',
            annualRevenue: 45000000,
            website: 'https://apexfin.com',
            city: 'New York',
            country: 'United States',
          },
          {
            id: 'comp_03',
            name: 'Starlight BioHealth',
            domain: 'starlightbio.org',
            industry: 'Healthcare',
            size: '51-200',
            annualRevenue: 12000000,
            website: 'https://starlightbio.org',
            city: 'Boston',
            country: 'United States',
          },
          {
            id: 'comp_04',
            name: 'Hyperion Cloud Logistics',
            domain: 'hyperionlogistics.net',
            industry: 'Logistics',
            size: '500+',
            annualRevenue: 98000000,
            website: 'https://hyperionlogistics.net',
            city: 'Berlin',
            country: 'Germany',
          },
          {
            id: 'comp_05',
            name: 'Catalyst Renewable Energy',
            domain: 'catalystenergy.co',
            industry: 'Clean Energy',
            size: '11-50',
            annualRevenue: 7200000,
            website: 'https://catalystenergy.co',
            city: 'Austin',
            country: 'United States',
          },
          {
            id: 'comp_06',
            name: 'Bluefin Commerce Group',
            domain: 'bluefincommerce.com',
            industry: 'E-Commerce',
            size: '51-200',
            annualRevenue: 28000000,
            website: 'https://bluefincommerce.com',
            city: 'London',
            country: 'United Kingdom',
          },
        ];

        return companiesData.map((comp, idx) => {
          const buffer = TemplateImageGenerator.generateCompanyLogoSvg(comp.name, comp.industry, idx);
          const filename = `${comp.domain.replace(/[^a-z0-9]/g, '_')}_logo.svg`;
          return {
            record: {
              id: comp.id,
              name: comp.name,
              domain: comp.domain,
              industry: comp.industry,
              size: comp.size,
              annualRevenue: comp.annualRevenue,
              logo: filename,
              website: comp.website,
              city: comp.city,
              country: comp.country,
            },
            files: [
              {
                fieldName: 'logo',
                filename,
                buffer,
                mimeType: 'image/svg+xml',
              },
            ],
          };
        });
      },
    },

    // 2. Leads
    {
      name: 'leads',
      dto: {
        name: 'leads',
        type: 'base',
        listRule: '@request.auth.id != ""',
        viewRule: '@request.auth.id != ""',
        createRule: '@request.auth.id != ""',
        updateRule: '@request.auth.id != ""',
        deleteRule: '@request.auth.id != ""',
        schema: [
          { id: 'f_lead_name', name: 'name', type: 'text', required: true },
          { id: 'f_lead_email', name: 'email', type: 'email', required: true },
          { id: 'f_lead_phone', name: 'phone', type: 'text' },
          { id: 'f_lead_comp', name: 'company', type: 'relation', options: { collectionId: 'companies' } },
          { id: 'f_lead_title', name: 'title', type: 'text' },
          {
            id: 'f_lead_status',
            name: 'status',
            type: 'select',
            options: { values: ['new', 'contacted', 'qualified', 'proposal', 'unqualified'] },
          },
          { id: 'f_lead_score', name: 'score', type: 'number' },
          {
            id: 'f_lead_source',
            name: 'source',
            type: 'select',
            options: { values: ['website', 'referral', 'linkedin', 'inbound_demo', 'cold_outreach'] },
          },
        ],
      },
      seed: async (_ctx: TemplateSeedContext): Promise<Array<Record<string, any>>> => {
        return [
          {
            id: 'lead_01',
            name: 'Alexander Pierce',
            email: 'a.pierce@nexusdigital.io',
            phone: '+1 (415) 890-1234',
            company: 'comp_01',
            title: 'VP of Platform Engineering',
            status: 'qualified',
            score: 92,
            source: 'inbound_demo',
          },
          {
            id: 'lead_02',
            name: 'Victoria Vance',
            email: 'v.vance@apexfin.com',
            phone: '+1 (212) 555-8765',
            company: 'comp_02',
            title: 'Chief Technology Officer',
            status: 'proposal',
            score: 98,
            source: 'referral',
          },
          {
            id: 'lead_03',
            name: 'Dr. Gregory House',
            email: 'ghouse@starlightbio.org',
            phone: '+1 (617) 432-9081',
            company: 'comp_03',
            title: 'Head of Clinical Informatics',
            status: 'contacted',
            score: 78,
            source: 'website',
          },
          {
            id: 'lead_04',
            name: 'Hannah Schmidt',
            email: 'hannah.s@hyperionlogistics.net',
            phone: '+49 30 901820',
            company: 'comp_04',
            title: 'Director of Global Supply Chain Tech',
            status: 'qualified',
            score: 86,
            source: 'linkedin',
          },
          {
            id: 'lead_05',
            name: 'Caleb Morgan',
            email: 'cmorgan@catalystenergy.co',
            phone: '+1 (512) 789-4321',
            company: 'comp_05',
            title: 'Chief Operations Officer',
            status: 'contacted',
            score: 64,
            source: 'cold_outreach',
          },
          {
            id: 'lead_06',
            name: 'Amelia Sterling',
            email: 'asterling@bluefincommerce.com',
            phone: '+44 20 7946 0912',
            company: 'comp_06',
            title: 'Head of E-Commerce Infrastructure',
            status: 'qualified',
            score: 89,
            source: 'inbound_demo',
          },
          {
            id: 'lead_07',
            name: 'Mateo Rossi',
            email: 'm.rossi@nexusdigital.io',
            phone: '+1 (415) 890-5678',
            company: 'comp_01',
            title: 'Principal Architect',
            status: 'new',
            score: 55,
            source: 'website',
          },
          {
            id: 'lead_08',
            name: 'Chloe Davenport',
            email: 'cdavenport@apexfin.com',
            phone: '+1 (212) 555-3412',
            company: 'comp_02',
            title: 'VP of Engineering Security',
            status: 'qualified',
            score: 91,
            source: 'referral',
          },
        ];
      },
    },

    // 3. Deals
    {
      name: 'deals',
      dto: {
        name: 'deals',
        type: 'base',
        listRule: '@request.auth.id != ""',
        viewRule: '@request.auth.id != ""',
        createRule: '@request.auth.id != ""',
        updateRule: '@request.auth.id != ""',
        deleteRule: '@request.auth.id != ""',
        schema: [
          { id: 'f_deal_title', name: 'title', type: 'text', required: true },
          { id: 'f_deal_comp', name: 'company', type: 'relation', options: { collectionId: 'companies' } },
          { id: 'f_deal_val', name: 'value', type: 'number', required: true },
          {
            id: 'f_deal_stage',
            name: 'stage',
            type: 'select',
            options: { values: ['discovery', 'qualification', 'proposal', 'negotiation', 'closed_won', 'closed_lost'] },
          },
          { id: 'f_deal_prob', name: 'probability', type: 'number' },
          { id: 'f_deal_close', name: 'expectedClose', type: 'text' },
        ],
      },
      seed: async (_ctx: TemplateSeedContext): Promise<Array<Record<string, any>>> => {
        return [
          {
            id: 'deal_01',
            title: 'Nexus Digital — Enterprise Stack License & SSE Cluster',
            company: 'comp_01',
            value: 65000,
            stage: 'negotiation',
            probability: 80,
            expectedClose: '2026-10-31',
          },
          {
            id: 'deal_02',
            title: 'Apex Financial — Multi-Tenant Embedded Ledger Engine',
            company: 'comp_02',
            value: 140000,
            stage: 'proposal',
            probability: 65,
            expectedClose: '2026-11-15',
          },
          {
            id: 'deal_03',
            title: 'Starlight BioHealth — HIPAA-Compliant Data Storage Pilot',
            company: 'comp_03',
            value: 32000,
            stage: 'qualification',
            probability: 45,
            expectedClose: '2026-11-30',
          },
          {
            id: 'deal_04',
            title: 'Hyperion Logistics — Global Fleet Telemetry Hub',
            company: 'comp_04',
            value: 220000,
            stage: 'closed_won',
            probability: 100,
            expectedClose: '2026-09-30',
          },
          {
            id: 'deal_05',
            title: 'Catalyst Renewable Energy — Microgrid Monitoring Hub',
            company: 'comp_05',
            value: 48000,
            stage: 'discovery',
            probability: 25,
            expectedClose: '2026-12-15',
          },
          {
            id: 'deal_06',
            title: 'Bluefin Commerce — High-Throughput Realtime Inventory Engine',
            company: 'comp_06',
            value: 95000,
            stage: 'negotiation',
            probability: 85,
            expectedClose: '2026-10-25',
          },
        ];
      },
    },

    // 4. Activities
    {
      name: 'activities',
      dto: {
        name: 'activities',
        type: 'base',
        listRule: '@request.auth.id != ""',
        viewRule: '@request.auth.id != ""',
        createRule: '@request.auth.id != ""',
        updateRule: '@request.auth.id != ""',
        deleteRule: '@request.auth.id != ""',
        schema: [
          {
            id: 'f_act_type',
            name: 'type',
            type: 'select',
            options: { values: ['call', 'meeting', 'email', 'note', 'task', 'demo'] },
          },
          { id: 'f_act_sub', name: 'subject', type: 'text', required: true },
          { id: 'f_act_notes', name: 'notes', type: 'text' },
          { id: 'f_act_comp', name: 'company', type: 'relation', options: { collectionId: 'companies' } },
          { id: 'f_act_deal', name: 'deal', type: 'relation', options: { collectionId: 'deals' } },
          {
            id: 'f_act_status',
            name: 'status',
            type: 'select',
            options: { values: ['pending', 'completed', 'cancelled'] },
          },
          { id: 'f_act_due', name: 'dueDate', type: 'text' },
        ],
      },
      seed: async (_ctx: TemplateSeedContext): Promise<Array<Record<string, any>>> => {
        return [
          {
            id: 'act_01',
            type: 'demo',
            subject: 'Executive Demo with VP Alexander Pierce',
            notes: 'Walked through embedded SQLite WAL performance and real-time SSE syncing. Alexander was impressed by sub-millisecond latency.',
            company: 'comp_01',
            deal: 'deal_01',
            status: 'completed',
            dueDate: '2026-10-01T15:00:00Z',
          },
          {
            id: 'act_02',
            type: 'meeting',
            subject: 'Security & Compliance Architecture Review',
            notes: 'Addressed encryption at rest and PocketBase-style granular row-level access rules. Security team signed off on POC.',
            company: 'comp_02',
            deal: 'deal_02',
            status: 'completed',
            dueDate: '2026-10-02T11:00:00Z',
          },
          {
            id: 'act_03',
            type: 'call',
            subject: 'Initial Discovery Call on Clinical Data Pipeline',
            notes: 'Discussed local-first edge nodes for lab devices. Needs 99.999% uptime with zero external cloud dependencies.',
            company: 'comp_03',
            deal: 'deal_03',
            status: 'completed',
            dueDate: '2026-10-03T14:30:00Z',
          },
          {
            id: 'act_04',
            type: 'email',
            subject: 'Send Master Services Agreement & Order Form',
            notes: 'Delivered final enterprise agreement with standard NET-30 terms. Waiting for legal countersignature.',
            company: 'comp_01',
            deal: 'deal_01',
            status: 'pending',
            dueDate: '2026-10-05T17:00:00Z',
          },
          {
            id: 'act_05',
            type: 'call',
            subject: 'Contract Wrap-up with Procurement',
            notes: 'Procurement confirmed PO #HP-8902 is approved and scheduled for wire transfer.',
            company: 'comp_04',
            deal: 'deal_04',
            status: 'completed',
            dueDate: '2026-09-29T10:00:00Z',
          },
          {
            id: 'act_06',
            type: 'meeting',
            subject: 'Technical Scoping: Bluefin Black Friday Traffic Spike',
            notes: 'Calculated projected throughput at 15,000 requests/sec. Embedded read replica caching satisfies requirement comfortably.',
            company: 'comp_06',
            deal: 'deal_06',
            status: 'pending',
            dueDate: '2026-10-06T16:00:00Z',
          },
        ];
      },
    },
  ],
};
