import { TemplateDefinition, TemplateSeedContext, SeedRecordResult } from '../types';
import { TemplateImageGenerator } from '../TemplateImageGenerator';

export const ecommerceTemplate: TemplateDefinition = {
  id: 'ecommerce',
  name: 'E-Commerce',
  tagline: 'Instant storefront with products, categories, orders & customer reviews',
  description:
    'Full-featured retail schema pre-seeded with 20 realistic products, custom generated SVG product images, relational categories, customer orders, and verified reviews.',
  icon: '🛒',
  badge: '20 Items & Images',
  aliases: ['ecommerce', 'e-commerce', 'shop', 'store'],
  stats: {
    collections: 4,
    records: 48,
    images: 25,
  },
  collections: [
    // 1. Categories
    {
      name: 'categories',
      dto: {
        name: 'categories',
        type: 'base',
        listRule: '',
        viewRule: '',
        createRule: '@request.auth.id != ""',
        updateRule: '@request.auth.id != ""',
        deleteRule: '@request.auth.id != ""',
        schema: [
          { id: 'f_cat_name', name: 'name', type: 'text', required: true },
          { id: 'f_cat_slug', name: 'slug', type: 'text', required: true, unique: true },
          { id: 'f_cat_desc', name: 'description', type: 'text' },
          { id: 'f_cat_icon', name: 'icon', type: 'text' },
          { id: 'f_cat_img', name: 'image', type: 'file' },
        ],
      },
      seed: async (_ctx: TemplateSeedContext): Promise<SeedRecordResult[]> => {
        const categoriesData = [
          {
            id: 'cat_electronics',
            name: 'Electronics',
            slug: 'electronics',
            description: 'Next-gen audio, mechanical peripherals, visual displays & creative hardware',
            icon: 'headphones',
          },
          {
            id: 'cat_accessories',
            name: 'Accessories & EDC',
            slug: 'accessories',
            description: 'Engineered backpacks, horology timepieces, titanium optics & leather goods',
            icon: 'backpack',
          },
          {
            id: 'cat_apparel',
            name: 'Footwear & Apparel',
            slug: 'apparel',
            description: 'Merino performance wear, trail running silhouettes & daily technical basics',
            icon: 'shoe',
          },
          {
            id: 'cat_homeliving',
            name: 'Home & Living',
            slug: 'home-living',
            description: 'Ergonomic workstations, artisan coffee drippers, ambient glow & desktop craft',
            icon: 'chair',
          },
          {
            id: 'cat_wellness',
            name: 'Beauty & Wellness',
            slug: 'wellness',
            description: 'Botanical night serums, clean self-care remedies & artisanal fragrance notes',
            icon: 'bottle',
          },
        ];

        return categoriesData.map((cat, idx) => {
          const buffer = TemplateImageGenerator.generateCategorySvg(cat.name, cat.icon, idx);
          const filename = `${cat.slug}_hero.svg`;
          return {
            record: {
              id: cat.id,
              name: cat.name,
              slug: cat.slug,
              description: cat.description,
              icon: cat.icon,
              image: filename,
            },
            files: [
              {
                fieldName: 'image',
                filename,
                buffer,
                mimeType: 'image/svg+xml',
              },
            ],
          };
        });
      },
    },

    // 2. Products (pre-seeded with 20 items & images!)
    {
      name: 'products',
      dto: {
        name: 'products',
        type: 'base',
        listRule: '',
        viewRule: '',
        createRule: '@request.auth.id != ""',
        updateRule: '@request.auth.id != ""',
        deleteRule: '@request.auth.id != ""',
        schema: [
          { id: 'f_prod_name', name: 'name', type: 'text', required: true },
          { id: 'f_prod_slug', name: 'slug', type: 'text', required: true, unique: true },
          { id: 'f_prod_desc', name: 'description', type: 'text' },
          { id: 'f_prod_price', name: 'price', type: 'number', required: true },
          { id: 'f_prod_stock', name: 'stock', type: 'number', required: true },
          {
            id: 'f_prod_cat',
            name: 'category',
            type: 'relation',
            options: { collectionId: 'categories' },
          },
          { id: 'f_prod_img', name: 'image', type: 'file', required: true },
          { id: 'f_prod_rating', name: 'rating', type: 'number' },
          { id: 'f_prod_featured', name: 'isFeatured', type: 'bool' },
          {
            id: 'f_prod_status',
            name: 'status',
            type: 'select',
            options: { values: ['in_stock', 'low_stock', 'out_of_stock', 'pre_order'] },
          },
        ],
      },
      seed: async (ctx: TemplateSeedContext): Promise<SeedRecordResult[]> => {
        const catMap = ctx.collectionIdMap;
        const categoriesId = catMap.get('categories') || 'categories';

        const rawProducts = [
          {
            id: 'prod_01',
            name: 'Aura Wireless ANC Headphones',
            slug: 'aura-wireless-anc-headphones',
            description: 'Custom 40mm titanium drivers with adaptive hybrid noise cancellation and 42-hour battery life.',
            price: 299.99,
            stock: 45,
            category: 'cat_electronics',
            rating: 4.9,
            isFeatured: true,
            status: 'in_stock',
            icon: 'headphones',
          },
          {
            id: 'prod_02',
            name: 'Keychron Lumina Mechanical Keyboard',
            slug: 'keychron-lumina-mechanical-keyboard',
            description: 'Gasket-mounted CNC aluminum chassis with hot-swappable lubricated tactile switches and RGB matrix.',
            price: 189.5,
            stock: 32,
            category: 'cat_electronics',
            rating: 4.8,
            isFeatured: true,
            status: 'in_stock',
            icon: 'keyboard',
          },
          {
            id: 'prod_03',
            name: 'ViewPro 27" Ultra-HD IPS Monitor',
            slug: 'viewpro-27-ultrahd-monitor',
            description: 'Factory-calibrated 4K display with 99% DCI-P3 color gamut, 90W USB-C power delivery and pivot stand.',
            price: 449.0,
            stock: 18,
            category: 'cat_electronics',
            rating: 4.7,
            isFeatured: false,
            status: 'in_stock',
            icon: 'monitor',
          },
          {
            id: 'prod_04',
            name: 'StudioWave USB-C Condenser Mic',
            slug: 'studiowave-usbc-condenser-mic',
            description: 'Broadcast-grade cardioid capsule with zero-latency headphone monitoring and integrated shockmount.',
            price: 129.0,
            stock: 50,
            category: 'cat_electronics',
            rating: 4.6,
            isFeatured: false,
            status: 'in_stock',
            icon: 'mic',
          },
          {
            id: 'prod_05',
            name: 'Halo Ambient Desk Smart Lightbar',
            slug: 'halo-ambient-desk-lightbar',
            description: 'Asymmetric optical glare-free design with wireless dial control and circadian auto-dimming.',
            price: 79.99,
            stock: 75,
            category: 'cat_electronics',
            rating: 4.5,
            isFeatured: false,
            status: 'in_stock',
            icon: 'lamp',
          },
          {
            id: 'prod_06',
            name: 'Nomad Waterproof Daypack 24L',
            slug: 'nomad-waterproof-daypack-24l',
            description: 'Cordura ballistic nylon with magnetic Fidlock buckles, dedicated 16" laptop sleeve and weatherproof zippers.',
            price: 149.0,
            stock: 38,
            category: 'cat_accessories',
            rating: 4.8,
            isFeatured: true,
            status: 'in_stock',
            icon: 'backpack',
          },
          {
            id: 'prod_07',
            name: 'Vanguard Chronograph Titanium Watch',
            slug: 'vanguard-chronograph-titanium-watch',
            description: 'Grade 5 aerospace titanium case, sapphire crystal with anti-reflective coating and Swiss meca-quartz movement.',
            price: 389.0,
            stock: 14,
            category: 'cat_accessories',
            rating: 4.9,
            isFeatured: true,
            status: 'in_stock',
            icon: 'watch',
          },
          {
            id: 'prod_08',
            name: 'Polaris Matte Acetate Sunglasses',
            slug: 'polaris-matte-acetate-sunglasses',
            description: 'Handcrafted Italian Mazzucchelli acetate with polarized category 3 lenses providing 100% UV400 defense.',
            price: 89.0,
            stock: 64,
            category: 'cat_accessories',
            rating: 4.4,
            isFeatured: false,
            status: 'in_stock',
            icon: 'glasses',
          },
          {
            id: 'prod_09',
            name: 'Heritage Bifold Leather Wallet',
            slug: 'heritage-bifold-leather-wallet',
            description: 'Vegetable-tanned full-grain Horween leather that develops a rich natural patina over years of daily carry.',
            price: 59.95,
            stock: 90,
            category: 'cat_accessories',
            rating: 4.7,
            isFeatured: false,
            status: 'in_stock',
            icon: 'wallet',
          },
          {
            id: 'prod_10',
            name: 'Carbon Minimalist RFID Cardholder',
            slug: 'carbon-minimalist-rfid-cardholder',
            description: 'Forged 3K matte carbon fiber plates with expandable silicone band holding up to 12 cards with RFID shield.',
            price: 39.0,
            stock: 120,
            category: 'cat_accessories',
            rating: 4.6,
            isFeatured: false,
            status: 'in_stock',
            icon: 'card',
          },
          {
            id: 'prod_11',
            name: 'Alpine Thermal Merino Wool Hoodie',
            slug: 'alpine-thermal-merino-hoodie',
            description: '100% 260gsm non-mulesed New Zealand merino wool engineered for thermoregulation and odor resistance.',
            price: 125.0,
            stock: 42,
            category: 'cat_apparel',
            rating: 4.9,
            isFeatured: true,
            status: 'in_stock',
            icon: 'hoodie',
          },
          {
            id: 'prod_12',
            name: 'TerraGrip Trail Running Shoes',
            slug: 'terragrip-trail-running-shoes',
            description: 'Vibram Megagrip outsole with responsive nitrogen-infused foam midsole and ripstop protective upper.',
            price: 165.0,
            stock: 26,
            category: 'cat_apparel',
            rating: 4.7,
            isFeatured: true,
            status: 'in_stock',
            icon: 'shoe',
          },
          {
            id: 'prod_13',
            name: 'AeroFlow Seamless Training Shirt',
            slug: 'aeroflow-seamless-training-shirt',
            description: 'Body-mapped ventilation zones and moisture-wicking synthetic blend designed for high-intensity movement.',
            price: 45.0,
            stock: 80,
            category: 'cat_apparel',
            rating: 4.5,
            isFeatured: false,
            status: 'in_stock',
            icon: 'shirt',
          },
          {
            id: 'prod_14',
            name: 'UrbanCraft Canvas Low-Top Sneakers',
            slug: 'urbancraft-canvas-lowtop-sneakers',
            description: 'Heavyweight organic cotton duck canvas with vulcanized gum rubber sole and ortholite cushioned footbed.',
            price: 79.0,
            stock: 35,
            category: 'cat_apparel',
            rating: 4.3,
            isFeatured: false,
            status: 'in_stock',
            icon: 'shoe',
          },
          {
            id: 'prod_15',
            name: 'Zenith Ergonomic Breathable Chair',
            slug: 'zenith-ergonomic-breathable-chair',
            description: 'Self-adjusting synchro-tilt mechanism, 4D armrests, dynamic lumbar support and breathable mesh weave.',
            price: 349.0,
            stock: 8,
            category: 'cat_homeliving',
            rating: 4.8,
            isFeatured: true,
            status: 'low_stock',
            icon: 'chair',
          },
          {
            id: 'prod_16',
            name: 'Komorebi Cedarwood Hand Candle',
            slug: 'komorebi-cedarwood-hand-candle',
            description: 'Hand-poured 100% natural soy wax with Japanese hinoki cedar, smoked amber, and unbleached cotton wick.',
            price: 34.0,
            stock: 95,
            category: 'cat_homeliving',
            rating: 4.9,
            isFeatured: false,
            status: 'in_stock',
            icon: 'candle',
          },
          {
            id: 'prod_17',
            name: 'Barista Precision Ceramic Dripper',
            slug: 'barista-precision-ceramic-dripper',
            description: 'Mino-yaki handcrafted ceramic pour-over funnel optimized for even thermal retention and extraction rate.',
            price: 48.0,
            stock: 40,
            category: 'cat_homeliving',
            rating: 4.7,
            isFeatured: false,
            status: 'in_stock',
            icon: 'coffee',
          },
          {
            id: 'prod_18',
            name: 'Nordic Solid Oak Floating Desk Riser',
            slug: 'nordic-solid-oak-desk-riser',
            description: 'FSC-certified solid European white oak with felt-lined aluminum legs and integrated cork cable channel.',
            price: 85.0,
            stock: 22,
            category: 'cat_homeliving',
            rating: 4.6,
            isFeatured: false,
            status: 'in_stock',
            icon: 'shelf',
          },
          {
            id: 'prod_19',
            name: 'Botanical Renewal Facial Night Oil',
            slug: 'botanical-renewal-facial-night-oil',
            description: 'Cold-pressed organic rosehip, squalane, blue tansy, and marula seed extract for nighttime barrier repair.',
            price: 58.0,
            stock: 60,
            category: 'cat_wellness',
            rating: 4.9,
            isFeatured: false,
            status: 'in_stock',
            icon: 'bottle',
          },
          {
            id: 'prod_20',
            name: 'Santal & Amber Organic Eau de Parfum',
            slug: 'santal-amber-organic-eau-de-parfum',
            description: 'Sustainably sourced Mysore sandalwood, warm labdanum amber, cardamon, and crisp bergamot notes.',
            price: 95.0,
            stock: 25,
            category: 'cat_wellness',
            rating: 4.8,
            isFeatured: true,
            status: 'in_stock',
            icon: 'perfume',
          },
        ];

        return rawProducts.map((p, idx) => {
          const buffer = TemplateImageGenerator.generateProductSvg(
            {
              title: p.name,
              category: p.category.replace('cat_', ''),
              price: p.price,
              icon: p.icon,
            },
            idx
          );
          const filename = `${p.slug}.svg`;

          return {
            record: {
              id: p.id,
              name: p.name,
              slug: p.slug,
              description: p.description,
              price: p.price,
              stock: p.stock,
              category: p.category,
              image: filename,
              rating: p.rating,
              isFeatured: p.isFeatured ? 1 : 0,
              status: p.status,
            },
            files: [
              {
                fieldName: 'image',
                filename,
                buffer,
                mimeType: 'image/svg+xml',
              },
            ],
          };
        });
      },
    },

    // 3. Orders
    {
      name: 'orders',
      dto: {
        name: 'orders',
        type: 'base',
        listRule: '@request.auth.id != ""',
        viewRule: '@request.auth.id != ""',
        createRule: '',
        updateRule: '@request.auth.id != ""',
        deleteRule: '@request.auth.id != ""',
        schema: [
          { id: 'f_ord_no', name: 'orderNumber', type: 'text', required: true, unique: true },
          { id: 'f_ord_cust', name: 'customerName', type: 'text', required: true },
          { id: 'f_ord_email', name: 'customerEmail', type: 'email', required: true },
          {
            id: 'f_ord_status',
            name: 'status',
            type: 'select',
            options: { values: ['pending', 'processing', 'shipped', 'delivered', 'cancelled'] },
          },
          { id: 'f_ord_total', name: 'total', type: 'number', required: true },
          { id: 'f_ord_items', name: 'items', type: 'json' },
          { id: 'f_ord_addr', name: 'shippingAddress', type: 'text' },
          {
            id: 'f_ord_pay',
            name: 'paymentStatus',
            type: 'select',
            options: { values: ['paid', 'pending', 'refunded', 'failed'] },
          },
        ],
      },
      seed: async (_ctx: TemplateSeedContext): Promise<Array<Record<string, any>>> => {
        return [
          {
            id: 'ord_1001',
            orderNumber: 'ORD-9801',
            customerName: 'Marcus Vance',
            customerEmail: 'marcus.vance@example.com',
            status: 'delivered',
            total: 359.98,
            items: JSON.stringify([
              { productId: 'prod_01', name: 'Aura Wireless ANC Headphones', quantity: 1, price: 299.99 },
              { productId: 'prod_09', name: 'Heritage Bifold Leather Wallet', quantity: 1, price: 59.95 },
            ]),
            shippingAddress: '742 Evergreen Terrace, Austin, TX 78701',
            paymentStatus: 'paid',
          },
          {
            id: 'ord_1002',
            orderNumber: 'ORD-9802',
            customerName: 'Elena Rodriguez',
            customerEmail: 'elena.rodriguez@techcorp.io',
            status: 'delivered',
            total: 638.5,
            items: JSON.stringify([
              { productId: 'prod_02', name: 'Keychron Lumina Mechanical Keyboard', quantity: 1, price: 189.5 },
              { productId: 'prod_03', name: 'ViewPro 27" Ultra-HD IPS Monitor', quantity: 1, price: 449.0 },
            ]),
            shippingAddress: '350 Fifth Ave, Floor 42, New York, NY 10118',
            paymentStatus: 'paid',
          },
          {
            id: 'ord_1003',
            orderNumber: 'ORD-9803',
            customerName: 'David Chen',
            customerEmail: 'david.chen@cloudstack.dev',
            status: 'shipped',
            total: 149.0,
            items: JSON.stringify([
              { productId: 'prod_06', name: 'Nomad Waterproof Daypack 24L', quantity: 1, price: 149.0 },
            ]),
            shippingAddress: '88 Market St, Suite 500, San Francisco, CA 94105',
            paymentStatus: 'paid',
          },
          {
            id: 'ord_1004',
            orderNumber: 'ORD-9804',
            customerName: 'Sarah Jenkins',
            customerEmail: 'sarah.jenkins@venturelab.net',
            status: 'processing',
            total: 474.0,
            items: JSON.stringify([
              { productId: 'prod_15', name: 'Zenith Ergonomic Breathable Chair', quantity: 1, price: 349.0 },
              { productId: 'prod_11', name: 'Alpine Thermal Merino Wool Hoodie', quantity: 1, price: 125.0 },
            ]),
            shippingAddress: '10 Downing St, London, UK SW1A 2AA',
            paymentStatus: 'paid',
          },
          {
            id: 'ord_1005',
            orderNumber: 'ORD-9805',
            customerName: 'Liam O\'Connor',
            customerEmail: 'liam.oconnor@acmemail.org',
            status: 'pending',
            total: 129.0,
            items: JSON.stringify([
              { productId: 'prod_04', name: 'StudioWave USB-C Condenser Mic', quantity: 1, price: 129.0 },
            ]),
            shippingAddress: '19 High St, Dublin, Ireland D08',
            paymentStatus: 'pending',
          },
          {
            id: 'ord_1006',
            orderNumber: 'ORD-9806',
            customerName: 'Sophia Kim',
            customerEmail: 'sophia.kim@startup.co',
            status: 'delivered',
            total: 153.0,
            items: JSON.stringify([
              { productId: 'prod_19', name: 'Botanical Renewal Facial Night Oil', quantity: 1, price: 58.0 },
              { productId: 'prod_20', name: 'Santal & Amber Organic Eau de Parfum', quantity: 1, price: 95.0 },
            ]),
            shippingAddress: '128 Technology Drive, Seattle, WA 98101',
            paymentStatus: 'paid',
          },
          {
            id: 'ord_1007',
            orderNumber: 'ORD-9807',
            customerName: 'Lucas Patel',
            customerEmail: 'lucas.patel@nexus.org',
            status: 'shipped',
            total: 210.0,
            items: JSON.stringify([
              { productId: 'prod_12', name: 'TerraGrip Trail Running Shoes', quantity: 1, price: 165.0 },
              { productId: 'prod_13', name: 'AeroFlow Seamless Training Shirt', quantity: 1, price: 45.0 },
            ]),
            shippingAddress: '456 Innovation Way, Toronto, ON M5V 2T6',
            paymentStatus: 'paid',
          },
          {
            id: 'ord_1008',
            orderNumber: 'ORD-9808',
            customerName: 'Emma Thompson',
            customerEmail: 'emma.t@example.com',
            status: 'delivered',
            total: 82.0,
            items: JSON.stringify([
              { productId: 'prod_16', name: 'Komorebi Cedarwood Hand Candle', quantity: 1, price: 34.0 },
              { productId: 'prod_17', name: 'Barista Precision Ceramic Dripper', quantity: 1, price: 48.0 },
            ]),
            shippingAddress: '221B Baker Street, London, UK NW1 6XE',
            paymentStatus: 'paid',
          },
        ];
      },
    },

    // 4. Reviews
    {
      name: 'reviews',
      dto: {
        name: 'reviews',
        type: 'base',
        listRule: '',
        viewRule: '',
        createRule: '',
        updateRule: '@request.auth.id != ""',
        deleteRule: '@request.auth.id != ""',
        schema: [
          {
            id: 'f_rev_prod',
            name: 'product',
            type: 'relation',
            options: { collectionId: 'products' },
          },
          { id: 'f_rev_author', name: 'author', type: 'text', required: true },
          { id: 'f_rev_rating', name: 'rating', type: 'number', required: true },
          { id: 'f_rev_title', name: 'title', type: 'text' },
          { id: 'f_rev_content', name: 'content', type: 'text', required: true },
          { id: 'f_rev_verified', name: 'verifiedPurchase', type: 'bool' },
        ],
      },
      seed: async (_ctx: TemplateSeedContext): Promise<Array<Record<string, any>>> => {
        return [
          {
            id: 'rev_01',
            product: 'prod_01',
            author: 'Marcus Vance',
            rating: 5,
            title: 'Incredible soundstage and ANC depth',
            content: 'The active noise cancellation blocks low rumble instantly on flights. Bluetooth multipoint switches between MacBook and iPhone seamlessly.',
            verifiedPurchase: 1,
          },
          {
            id: 'rev_02',
            product: 'prod_01',
            author: 'Chloe Adams',
            rating: 5,
            title: 'Worth every penny for focus work',
            content: 'Battery lasts the entire work week without charging. The memory foam cushions breathe well even during 8-hour sprint sessions.',
            verifiedPurchase: 1,
          },
          {
            id: 'rev_03',
            product: 'prod_02',
            author: 'Elena Rodriguez',
            rating: 5,
            title: 'The acoustic profile is pristine',
            content: 'Factory lubrication on the switches gives a deep, satisfying thock without pinging. Keycaps have crisp legends and nice texture.',
            verifiedPurchase: 1,
          },
          {
            id: 'rev_04',
            product: 'prod_03',
            author: 'David Chen',
            rating: 4,
            title: 'Stunning color reproduction',
            content: '99% DCI-P3 is noticeable for color grading and design reviews. The 90W single-cable USB-C connection powers my laptop flawlessly.',
            verifiedPurchase: 1,
          },
          {
            id: 'rev_05',
            product: 'prod_06',
            author: 'Alex Taylor',
            rating: 5,
            title: 'Ideal minimalist everyday carry',
            content: 'Survived heavy rain in Tokyo with electronics completely dry. The Fidlock magnetic buckles snap into place with one hand.',
            verifiedPurchase: 1,
          },
          {
            id: 'rev_06',
            product: 'prod_07',
            author: 'Gabriel Scott',
            rating: 5,
            title: 'Lightweight titanium elegance',
            content: 'The titanium weight is astonishingly light on the wrist. Anti-reflective sapphire coating makes the dial readable under direct sunlight.',
            verifiedPurchase: 1,
          },
          {
            id: 'rev_07',
            product: 'prod_11',
            author: 'Sarah Jenkins',
            rating: 5,
            title: 'My absolute go-to travel layer',
            content: 'Super soft merino wool with zero scratchiness. Naturally odor-resistant after 3 days of backcountry trekking.',
            verifiedPurchase: 1,
          },
          {
            id: 'rev_08',
            product: 'prod_12',
            author: 'Lucas Patel',
            rating: 5,
            title: 'Unbelievable traction on wet rock',
            content: 'The Megagrip lugs bite into loose mud and wet granite with immense confidence. Toe cap protection prevents painful stubs.',
            verifiedPurchase: 1,
          },
          {
            id: 'rev_09',
            product: 'prod_15',
            author: 'Julian King',
            rating: 5,
            title: 'Saved my lower back',
            content: 'The dynamic lumbar support engages naturally when reclining. The mesh seat remains cool through hot summer afternoons.',
            verifiedPurchase: 1,
          },
          {
            id: 'rev_10',
            product: 'prod_16',
            author: 'Emma Thompson',
            rating: 5,
            title: 'Subtle and grounding scent',
            content: 'Not overpowering like synthetic candles. Fills the room with authentic cedarwood and hinoki forest notes.',
            verifiedPurchase: 1,
          },
          {
            id: 'rev_11',
            product: 'prod_17',
            author: 'Nathan Green',
            rating: 5,
            title: 'Perfect pour-over consistency',
            content: 'Rib geometry produces balanced flow rates and clean cup clarity. The ceramic matte glaze looks gorgeous on the coffee bar.',
            verifiedPurchase: 1,
          },
          {
            id: 'rev_12',
            product: 'prod_19',
            author: 'Sophia Kim',
            rating: 5,
            title: 'Skin feels replenished by morning',
            content: 'Non-comedogenic oil that sinks right in without a greasy film. Calms redness overnight significantly.',
            verifiedPurchase: 1,
          },
          {
            id: 'rev_13',
            product: 'prod_20',
            author: 'Zoe Martinez',
            rating: 5,
            title: 'Sophisticated and long-lasting',
            content: 'Warm sandalwood and amber with a crisp opening. Projects gently without being cloying.',
            verifiedPurchase: 1,
          },
          {
            id: 'rev_14',
            product: 'prod_04',
            author: 'Hannah Lee',
            rating: 4,
            title: 'Great clarity for podcasts & voice calls',
            content: 'Picks up vocal warmth while rejecting background keyboard clatter. Direct USB-C plug and play on Mac and Windows.',
            verifiedPurchase: 1,
          },
          {
            id: 'rev_15',
            product: 'prod_05',
            author: 'Amelia Clark',
            rating: 5,
            title: 'Eliminated eye strain at night',
            content: 'Front desk surface is illuminated brightly while leaving the monitor completely glare-free. The wireless dial is so satisfying.',
            verifiedPurchase: 1,
          },
        ];
      },
    },
  ],
};
