import { CollectionModel } from './models/Collection';
import { SchemaField } from './models/Field';
import { SchemaService } from './SchemaService';

export class TypeGenerator {
  constructor(private schemaService: SchemaService) {}

  /**
   * Generates TypeScript definitions from current schema collections.
   */
  public generate(): string {
    const collections = this.schemaService.getAllCollections();
    return TypeGenerator.generateFromCollections(collections);
  }

  /**
   * Pure static generator that transforms a list of CollectionModel into
   * a self-contained TypeScript definitions string.
   */
  public static generateFromCollections(collections: CollectionModel[]): string {
    const lines: string[] = [];

    // Header comment
    lines.push('/**',
      ' * Auto-Generated TypeScript Definitions for NodeStack',
      ' * ',
      ' * Generated by: nodestack typegen',
      ` * Generated at: ${new Date().toISOString()}`,
      ' * ',
      ' * DO NOT EDIT DIRECTLY. Regenerate using:',
      ' *   npx nodestack typegen > nodestack-types.ts',
      ' */',
      ''
    );

    // Standard base models & utilities
    lines.push(
      '// ==========================================',
      '// Base System Types',
      '// ==========================================',
      '',
      'export interface BaseSystemFields {',
      '  id: string;',
      '  created: string;',
      '  updated: string;',
      '}',
      '',
      'export interface AuthSystemFields extends BaseSystemFields {',
      '  email: string;',
      '  emailVisibility: boolean;',
      '  verified: boolean;',
      '}',
      '',
      'export interface RecordModel extends BaseSystemFields {',
      '  [key: string]: any;',
      '}',
      '',
      'export interface AdminModel extends BaseSystemFields {',
      '  email: string;',
      '  avatar?: string;',
      '}',
      '',
      'export interface ListResult<T = any> {',
      '  page: number;',
      '  perPage: number;',
      '  totalItems: number;',
      '  totalPages: number;',
      '  items: T[];',
      '}',
      ''
    );

    lines.push(
      '// ==========================================',
      '// Collection Records & Responses',
      '// ==========================================',
      ''
    );

    const collectionMapEntries: Array<{ name: string; recordName: string; responseName: string }> = [];

    // Map each collection
    for (const col of collections) {
      const pascalName = this.toPascalCase(col.name);
      const recordName = `${pascalName}Record`;
      const expandName = `${pascalName}Expand`;
      const responseName = `${pascalName}Response`;

      collectionMapEntries.push({
        name: col.name,
        recordName,
        responseName,
      });

      // 1. Field option types (e.g. select values enum/union)
      const optionTypes: string[] = [];
      const fieldsToRender: Array<{ name: string; typeStr: string; required: boolean }> = [];
      const relationFields: Array<{ name: string; targetColName?: string; isMulti: boolean }> = [];

      const systemFieldsToSkip = new Set(['id', 'created', 'updated']);
      if (col.type === 'auth') {
        systemFieldsToSkip.add('email');
        systemFieldsToSkip.add('emailVisibility');
        systemFieldsToSkip.add('verified');
        systemFieldsToSkip.add('passwordHash');
        systemFieldsToSkip.add('tokenKey');
      }

      for (const field of col.schema) {
        if (systemFieldsToSkip.has(field.name)) {
          continue;
        }

        const isMulti = Boolean(field.options?.maxSelect && field.options.maxSelect > 1);

        // Collect relations for Expand type
        if (field.type === 'relation') {
          const targetCol = collections.find(
            (c) => c.id === field.options?.collectionId || c.name === field.options?.collectionId
          );
          relationFields.push({
            name: field.name,
            targetColName: targetCol?.name,
            isMulti,
          });
        }

        const typeStr = this.getFieldTsType(field, pascalName, optionTypes);
        fieldsToRender.push({
          name: field.name,
          typeStr,
          required: Boolean(field.required),
        });
      }

      // Output option types if any
      if (optionTypes.length > 0) {
        lines.push(...optionTypes, '');
      }

      // 2. Collection Record Interface
      const baseInterface = col.type === 'auth' ? 'AuthSystemFields' : 'BaseSystemFields';
      lines.push(`export interface ${recordName} extends ${baseInterface} {`);
      for (const f of fieldsToRender) {
        const formattedName = this.formatPropertyName(f.name);
        const optionalFlag = f.required ? '' : '?';
        lines.push(`  ${formattedName}${optionalFlag}: ${f.typeStr};`);
      }
      lines.push('}', '');

      // 3. Collection Expand Type
      if (relationFields.length > 0) {
        lines.push(`export type ${expandName} = {`);
        for (const rel of relationFields) {
          const formattedName = this.formatPropertyName(rel.name);
          let targetType = 'Record<string, any>';
          if (rel.targetColName) {
            const targetPascal = this.toPascalCase(rel.targetColName);
            targetType = `${targetPascal}Response`;
          }
          if (rel.isMulti) {
            targetType = `${targetType}[]`;
          }
          lines.push(`  ${formattedName}?: ${targetType};`);
        }
        lines.push('};', '');

        // 4. Collection Response Type (with default expand)
        lines.push(
          `export type ${responseName}<TExpand = ${expandName}> = ${recordName} & {`,
          '  expand?: TExpand;',
          '};',
          ''
        );
      } else {
        lines.push(
          `export type ${expandName} = Record<string, unknown>;`,
          '',
          `export type ${responseName}<TExpand = unknown> = ${recordName} & {`,
          '  expand?: TExpand;',
          '};',
          ''
        );
      }
    }

    // Schema Collections Map
    lines.push(
      '// ==========================================',
      '// Schema Collections Map',
      '// ==========================================',
      '',
      'export interface SchemaCollections {'
    );
    for (const entry of collectionMapEntries) {
      lines.push(`  ${this.formatPropertyName(entry.name)}: ${entry.recordName};`);
    }
    lines.push('}', '');

    lines.push('export interface SchemaCollectionResponses {');
    for (const entry of collectionMapEntries) {
      lines.push(`  ${this.formatPropertyName(entry.name)}: ${entry.responseName};`);
    }
    lines.push('}', '');

    lines.push(
      'export type Collections = SchemaCollections;',
      'export type CollectionResponses = SchemaCollectionResponses;',
      'export type CollectionName = keyof SchemaCollections;',
      '',
      'export type TypedRecord<T extends CollectionName> = CollectionResponses[T];',
      ''
    );

    return lines.join('\n');
  }

  private static getFieldTsType(
    field: SchemaField,
    colPascal: string,
    outOptionTypes: string[]
  ): string {
    const isMulti = Boolean(field.options?.maxSelect && field.options.maxSelect > 1);

    switch (field.type) {
      case 'text':
      case 'email':
      case 'url':
      case 'date':
        return 'string';
      case 'number':
        return 'number';
      case 'bool':
        return 'boolean';
      case 'json':
        return 'any';
      case 'file':
        return isMulti ? 'string[]' : 'string';
      case 'relation':
        return isMulti ? 'string[]' : 'string';
      case 'select': {
        if (
          field.options?.values &&
          Array.isArray(field.options.values) &&
          field.options.values.length > 0
        ) {
          const typeName = `${colPascal}${this.toPascalCase(field.name)}Options`;
          const union = field.options.values
            .map((v: string) => `'${String(v).replace(/'/g, "\\'")}'`)
            .join(' | ');
          outOptionTypes.push(`export type ${typeName} = ${union};`);
          return isMulti ? `${typeName}[]` : typeName;
        }
        return isMulti ? 'string[]' : 'string';
      }
      default:
        return 'any';
    }
  }

  private static toPascalCase(str: string): string {
    if (!str) return 'Item';
    const cleaned = str.replace(/[^a-zA-Z0-9]+(.)/g, (_, chr) => chr.toUpperCase());
    const result = cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
    return /^[a-zA-Z_$]/.test(result) ? result : `Col_${result}`;
  }

  private static formatPropertyName(name: string): string {
    if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)) {
      return name;
    }
    return JSON.stringify(name);
  }
}
